config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/reviews/filter', to: 'reviews#filter'
  get '/trains/filter', to: 'trains#filter'
  get '/trains/search_train', to: 'trains#search_train', as: 'search_train'
  get 'signup', to: "passengers#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]
  resources :admins
  resources :trains
  resources :tickets
  resources :reviews
  resources :passengers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>">
  <p>
    <strong>Username:</strong>
    <%= admin.username %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= admin.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= admin.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= admin.password %>
  </p>

  <p>
    <strong>Phone num:</strong>
    <%= admin.phone_num %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= admin.address %>
  </p>

  <p>
    <strong>Card num:</strong>
    <%= admin.card_num %>
  </p>

</div>

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :phone_num, style: "display: block" %>
    <%= form.text_field :phone_num %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :card_num, style: "display: block" %>
    <%= form.text_field :card_num %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Show this admin", @admin %> |
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Admins</h1>

<div id="admins">
  <% @admins.each do |admin| %>
    <%= render admin %>
    <p>
      <%= link_to "Show this admin", admin %>
    </p>
  <% end %>
</div>

<%= link_to "New admin", new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin %>

<div>
  <%= link_to "Edit this admin", edit_admin_path(@admin) %> |
  <%= link_to "Back to admins", admins_path %>

  <%= button_to "Destroy this admin", @admin, method: :delete %>
</div>