config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/reviews/filter', to: 'reviews#filter'
  get '/trains/filter', to: 'trains#filter'
  get '/trains/search_train', to: 'trains#search_train', as: 'search_train'
  get 'signup', to: "passengers#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]
  resources :admins
  resources :trains
  resources :tickets
  resources :reviews
  resources :passengers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/train.rb
class Train < ApplicationRecord
    has_many :ticket, dependent: :destroy
    has_many :review, dependent: :destroy
    validates :train_num, presence: true, format: { with: /\A\d+\z/, message: "only allows numbers", greater_than_or_equal_to: 0 }
    validates :departure_date, presence: true
    validates :departure_st, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "should be only alphabets" }
    validates :departure_time, presence: true
    validates :terminal_st, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "should be only alphabets" }
    validates :arrival_date, presence: true
    validates :arrival_time, presence: true
    validates :ticket_price, presence: true, numericality: {greater_than_or_equal_to: 0}
    validates :train_capacity, presence: true, numericality: {greater_than_or_equal_to: 0}
    validates :seats_left, presence: true, numericality: { less_than_or_equal_to: :train_capacity, greater_than_or_equal_to: 0 }
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[ show edit update destroy ], except: [:search_train]

  # GET /trains or /trains.json
  def index
    @trains = Train.all
      # get/calculate the train ratings
      @trains.each do |train|
        if Review.where(train_id: train.id).count > 0
          train.rating = Review.where(train_id: train.id).sum(:rating) / Review.where(train_id: train.id).count
          train.update_column(:rating, train.rating)
        end
      end
  end

  # GET /trains/1 or /trains/1.json
  def show
      end

  # GET /trains/new
  def new
        @train = Train.new
  end

  # GET /trains/1/edit
  def edit
      end

  # POST /trains or /trains.json
  def create
    @train = Train.new(train_params)
    
    respond_to do |format|
      if @train.save
        format.html { redirect_to train_url(@train), notice: "Train was successfully created." }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1 or /trains/1.json
  def update
        respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to train_url(@train), notice: "Train was successfully updated." }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1 or /trains/1.json
  def destroy

    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Train was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def filter
    # train filter
    departure_st = params[:departure_st]
    terminal_st = params[:terminal_st]
    rating = params[:rating]
    @trains = Train.all
    if departure_st.present?
      @trains = @trains.where(departure_st: departure_st)
    end
    if terminal_st.present?
      @trains = @trains.where(terminal_st: terminal_st)
    end
    if rating.present?
      @trains = @trains.where('rating >=?', rating)
    end
    render 'index'
  end

  def search_train
    # search booked passengers based on train number - only for admin
    train_num = params[:train_num]
    @train = Train.find_by_train_num(train_num)
    if @train.present?
      @tickets = Ticket.where(train_id: @train.id)
    else
      @tickets = []
    end
    render 'trains/search_train'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def train_params
      params.require(:train).permit(:train_num, :departure_st, :terminal_st, :departure_date, :departure_time, :arrival_date, :arrival_time, :ticket_price, :train_capacity, :seats_left)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<style>
    /* Form container */
    .train-form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        background-color: #f9f9f9;
        border-radius: 5px;
    }

    /* Error message */
    .error-message {
        color: red;
    }

    /* Form group */
    .form-group {
        margin-bottom: 15px;
        margin-right: 20px;
    }

    /* Label styles */
    .form-group label {
        display: block;
        font-weight: bold;
    }

    /* Input styles */
    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    /* Submit button */
    .btn-primary {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

</style>
<%= form_with(model: train, class: 'train-form') do |form| %>
  <% if train.errors.any? %>
    <div class="error-message">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>
      <ul>
        <% train.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :train_num %>
    <%= form.number_field :train_num, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :departure_st %>
    <%= form.text_field :departure_st, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :terminal_st %>
    <%= form.text_field :terminal_st, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :departure_date %>
    <%= form.date_field :departure_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :departure_time %>
    <%= form.time_field :departure_time, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :arrival_date %>
    <%= form.date_field :arrival_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :arrival_time %>
    <%= form.time_field :arrival_time, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :ticket_price %>
    <%= form.text_field :ticket_price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :train_capacity %>
    <%= form.number_field :train_capacity, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :seats_left %>
    <%= form.number_field :seats_left, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<style>
    .vertical-table {
        border-collapse: collapse;
        width: 50%;
        margin: 0 auto;
    }

    .vertical-table td {
        padding: 8px;
        border-bottom: 1px solid #ddd;
    }

    .vertical-table td:first-child {
        font-weight: bold;
        width: 50%;
    }

    .vertical-table td:last-child {
        text-align: left;
    }

    .vertical-table tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .vertical-table td strong {
        font-weight: bold;
    }
</style>


<div id="<%= dom_id train %>">
  <table class="vertical-table">
    <tr>
      <td><strong>Train num:</strong></td>
      <td><%= train.train_num %></td>
    </tr>
    <tr>
      <td><strong>Departure st:</strong></td>
      <td><%= train.departure_st %></td>
    </tr>
    <tr>
      <td><strong>Terminal st:</strong></td>
      <td><%= train.terminal_st %></td>
    </tr>
    <tr>
      <td><strong>Departure date:</strong></td>
      <td><%= train.departure_date %></td>
    </tr>
    <tr>
      <td><strong>Departure time:</strong></td>
      <td><%= train.departure_time %></td>
    </tr>
    <tr>
      <td><strong>Arrival date:</strong></td>
      <td><%= train.arrival_date %></td>
    </tr>
    <tr>
      <td><strong>Arrival time:</strong></td>
      <td><%= train.arrival_time %></td>
    </tr>
    <tr>
      <td><strong>Ticket price:</strong></td>
      <td><%= train.ticket_price %></td>
    </tr>
    <tr>
      <td><strong>Train capacity:</strong></td>
      <td><%= train.train_capacity %></td>
    </tr>
    <tr>
      <td><strong>Seats left:</strong></td>
      <td><%= train.seats_left %></td>
    </tr>
  </table>
</div>

app/views/trains/edit.html.erb
<h1>Editing train</h1>

<%= render "form", train: @train %>

<br>

<div>
  <%= link_to "Show this train", @train %> |
  <%= link_to "Back to trains", trains_path %>
</div>

app/views/trains/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railway Ticketing System</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <style>
      body {
          font-family: Arial, sans-serif;
          background-color: #f4f4f4;
          margin: 0;
          padding: 0;
      }

      header {
          background-color: #007bff;
          color: #fff;
          padding: 10px;
          text-align: center;
      }

      h1 {
          text-align: center;
          margin-bottom: 20px;
          color: #333;
      }

      .container {
          margin: 0 auto;
          padding: 20px;
          background-color: #fff;
          border: 1px solid #ccc;
          border-radius: 5px;
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }

      .notice {
          color: green;
          text-align: center;
      }

      table {
          width: 100%;
          border-collapse: collapse;
          border: 1px solid #ddd;
      }

      th, td {
          padding: 8px;
          text-align: left;
          border-bottom: 1px solid #ddd;
      }

      th {
          background-color: #f2f2f2;
      }

      tr:nth-child(even) {
          background-color: #f2f2f2;
      }

      .filter-form {
          max-width: 400px;
          margin: 20px 10px;
          padding: 10px;
          background-color: #f2f2f2;
          border-radius: 5px;
      }

      .form-group {
          margin-bottom: 10px;
          margin-right: 20px;
      }

      .form-control {
          width: 100%;
          padding: 8px;
          border: 1px solid #ccc;
          border-radius: 5px;
      }

      .btn-primary {
          background-color: #007bff;
          color: #fff;
          border: none;
          padding: 10px 20px;
          border-radius: 5px;
          cursor: pointer;
      }

      .btn-primary:hover {
          background-color: #0056b3;
      }
      .no-decoration{
          text-decoration: none;
      }
  </style>
</head>

<body>

<div class="container">
  <p class="notice"><%= notice %></p>

  <% if current_user.is_admin == true %>
    <%= link_to "New Train", new_train_path, class: 'no-decoration btn-primary' %>
  <% end %>

  <%= form_tag('/trains/filter', method: 'get', class: 'filter-form') do %>
    <div class="form-group">
      <%= label_tag 'departure_st', 'Departure Station' %>
      <%= text_field_tag 'departure_st', params[:departure_st], class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag 'terminal_st', 'Terminal Station' %>
      <%= text_field_tag 'terminal_st', params[:terminal_st], class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag 'rating', 'Rating' %>
      <%= text_field_tag 'rating', params[:rating], class: 'form-control' %>
    </div>

    <%= submit_tag 'Filter', class: 'btn btn-primary' %>
  <% end %>

  <table>
    <thead>
    <tr>
      <th>Train number</th>
      <th>Departure station</th>
      <th>Departure date</th>
      <th>Departure Time</th>
      <th>Arrival Station</th>
      <th>Arrival Date</th>
      <th>Arrival time</th>
      <th>Ticket price</th>
      <th>Seats left</th>
      <th>Rating</th>
      <th colspan="4">Actions</th>
    </tr>
    </thead>

    <% if @trains.present? %>
      <tbody>
      <% @trains.each do |train| %>
        <% if current_user.is_admin == true || (train.departure_date >= Date.today && train.seats_left > 0) %>
          <tr>
            <td><%= train.train_num %></td>
            <td><%= train.departure_st %></td>
            <td><%= train.departure_date.strftime('%m/%d/%Y') %></td>
            <td><%= train.departure_time.strftime("%I:%M %p") %></td>
            <td><%= train.terminal_st %></td>
            <td><%= train.arrival_date.strftime('%m/%d/%Y') %></td>
            <td><%= train.arrival_time.strftime("%I:%M %p") %></td>
            <td><%= train.ticket_price %></td>
            <td><%= train.seats_left %></td>
            <td><%= train.rating %></td>
            <td><%= link_to 'Show', train %></td>
            <td><%= link_to 'Book', new_ticket_path(:train_id => train.id) %></td>
            <% if current_user.is_admin == true %>
              <td><%= link_to 'Edit', edit_train_path(train) %></td>
              <td><%= link_to "Delete", train_path(train), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    <% else %>
      <tbody>
      <tr>
        <td colspan="11">No trains found</td>
      </tr>
      </tbody>
    <% end %>
  </table>
</div>
</body>
</html>

app/views/trains/new.html.erb
<h1>New train</h1>

<%= render "form", train: @train %>

<br>

<div>
  <%= link_to "Back to trains", trains_path %>
</div>

app/views/trains/search_train.html.erb
<style>

    .container {
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .notice {
        color: green;
        text-align: center;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        border: 1px solid #ddd;
    }

    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .filter-form {
        max-width: 400px;
        margin: 20px 10px;
        padding: 10px;
        background-color: #f2f2f2;
        border-radius: 5px;
    }

    .form-group {
        margin-bottom: 10px;
        margin-right: 20px;
    }

    .form-control {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
    .no-decoration{
        text-decoration: none;
    }
</style>
<div class="container">
<p style="color: green"><%= notice %></p>

<%= form_tag('/trains/search_train', method: 'get', class: 'filter-form') do %>
  <div class="form-group">
    <%= label_tag "train_num", 'Search Train Number' %>
    <%= text_field_tag 'train_num', params[:train_num], class: 'form-control' %>
  </div>
  <%= submit_tag 'Filter', class: 'btn btn-primary' %>
<% end %>

<table>
  <thead>
  <tr>
    <th>Username</th>
    <th>Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Address</th>
    <th>Card Number</th>
    <th>Confirmation Number</th>
  </tr>
  </thead>

  <% if @tickets.present? %>
  <tbody>
  <% @tickets.each do |ticket| %>
      <tr>
        <td ><%= ticket.passenger.username %></td>
        <td><%= ticket.passenger.name %></td>
        <td><%= ticket.passenger.email %></td>
        <td><%= ticket.passenger.phone_num   %></td>
        <td><%= ticket.passenger.address %></td>
        <td><%= ticket.passenger.card_num%></td>
        <td><%= ticket.confirm_num %></td>
      </tr>
    <%end %>
  </tbody>
  <% else %>
    <tbody>
    <tr>
      <td colspan="7">No users found</td>
    </tr>
      </tbody>
    <%end %>

</table>
</div>

app/views/trains/show.html.erb
<style>
    .btn-primary {
        text-decoration: none;
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
    .action{
        margin-top: 10px;
        display: flex;
        width: 100%;
        justify-content: center;
        gap: 5px;
        align-items: center;
    }
</style>

<p style="color: green"><%= notice %></p>

<%= render @train %>

<div class="action">
  <% if current_user.is_admin == true%>
    <%= link_to 'Edit', edit_train_path(@train), class: "btn-primary"%>
    <%= link_to "Delete", train_path(@train), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } , class: "btn-primary" %>
  <% end %>
  <%= link_to "Back to trains", trains_path , class: "btn-primary" %>
</div>