config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/reviews/filter', to: 'reviews#filter'
  get '/trains/filter', to: 'trains#filter'
  get '/trains/search_train', to: 'trains#search_train', as: 'search_train'
  get 'signup', to: "passengers#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]
  resources :admins
  resources :trains
  resources :tickets
  resources :reviews
  resources :passengers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all

  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    # setting the passenger who has written the review
    @review.passenger = current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def filter
    # review filtering
    passenger_name = params[:name]
    train_num = params[:train_num]
    @reviews = Review.all
    if passenger_name.present? || train_num.present?
      # Apply filtering logic only if filtering parameters are present
      @reviews = Review.all
      if passenger_name.present?
        # filtering by passenger name
        @reviews = @reviews.joins(:passenger).where('passengers.name LIKE ?', "%#{passenger_name}%")
      end
      if train_num.present?
        # filtering by train number
        @reviews = @reviews.joins(:train).where('trains.train_num = ?', train_num)
      end
    end
    # re-rendering the index page
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
        @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :feedback, :train_id, :name, :train_num)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<style>
    /* CSS for the review form */
    .review-form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ddd;
        background-color: #f5f5f5;
        border-radius: 5px;
    }

    .form-group {
        margin-bottom: 15px;
        margin-right: 20px;
    }

    label {
        font-weight: bold;
    }

    input[type="number"],
    textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
        margin-top: 5px;
    }

    .error-messages {
        color: red;
        margin-bottom: 15px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

</style>

<%= form_with(model: review, class: 'review-form') do |form| %>
  <% if review.errors.any? %>
    <div class="error-messages">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.hidden_field :train_id, value: params[:train_id] %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="form-group">
    <%= form.label :feedback %>
    <%= form.text_area :feedback, rows: 4 %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn-primary' %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<style>
    /* CSS for the review table */
    .review-table {
        border-collapse: collapse;
        width: 300px;
        margin: 20px auto;
        border: 1px solid #ddd;
        border-radius: 5px;
    }

    .review-table td {
        padding: 10px;
        border-bottom: 1px solid #ddd;
    }

    .review-table td:first-child {
        font-weight: bold;
        width: 50%;
        background-color: #f2f2f2;
    }

    .review-table td:last-child {
        width: 50%;
    }

    .review-table tr:last-child td {
        border-bottom: none;
    }


</style>

<table class="review-table">
  <tr>
    <td><strong>Rating:</strong></td>
    <td><%= review.rating %></td>
  </tr>
  <tr>
    <td><strong>Feedback:</strong></td>
    <td><%= review.feedback %></td>
  </tr>
</table>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
    }

    header {
        background-color: #007bff;
        color: #fff;
        padding: 10px;
        text-align: center;
    }

    h1 {
        text-align: center;
        margin-bottom: 20px;
        color: #333;
    }

    .container {
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .notice {
        color: green;
        text-align: center;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        border: 1px solid #ddd;
    }

    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .filter-form {
        max-width: 400px;
        margin: 20px 10px;
        padding: 10px;
        background-color: #f2f2f2;
        border-radius: 5px;
    }

    .form-group {
        margin-bottom: 10px;
        margin-right: 20px;
    }

    .form-control {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
    .no-decoration{
        text-decoration: none;
    }
</style>

<div class="container">
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<%= form_tag('/reviews/filter', method: 'get', class: 'filter-form') do %>
  <div class="form-group">
    <%= label_tag 'name', 'Name' %>
    <%= text_field_tag 'name', params[:name], class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag 'train_num', 'Train Number' %>
    <%= text_field_tag 'train_num', params[:train_num], class: 'form-control' %>
  </div>

  <%= submit_tag 'Filter', class: 'btn btn-primary' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Train Number</th>
      <th>Passenger</th>
      <th>Rating</th>
      <th colspan="10"></th>
    </tr>
  </thead>
  <%if @reviews.present?%>
    <tbody>
      <% @reviews.each do |review| %>
      <tr>
        <td><%= review.train.train_num %></td>
        <td><%= review.passenger.name %></td>
        <td><%= review.rating %></td>
        <td><%= link_to 'Show', review %></td>
        <% if  current_user.is_admin == true %>
          <% if  current_user.id == review.passenger_id || current_user.is_admin == true%>
            <td><%= link_to 'Edit', edit_review_path(review, train_id: review.train_id)%></td>
          <% end %>
          <td>
            <%= link_to "Delete", review_path(review), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            } %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  <%else%>
    <tbody>
      <tr>
        <td colspan="5">No reviews found</td>
      </tr>
    </tbody>
  <%end%>
</table>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <% if current_user.is_admin == true || current_user.id == @review.passenger_id %>
    <td><%= link_to 'Edit', edit_review_path(@review, train_id: @review.train_id)%></td>
  <% end %>
  <%= link_to "Delete", review_path(@review), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
  <%= link_to "Back to reviews", reviews_path %>
</div>